services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: football
      MYSQL_USER: football
      MYSQL_PASSWORD: footballpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  data_manager:
    build: data_manager/.
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: football
      MYSQL_PASSWORD: footballpassword
      FOOTBALL_API_TOKEN: 09c05f78fa8a44f8a2343532c1945ee6
      MYSQL_DATABASE: football
  
  backend:
      build: backend/.
      depends_on:
        mysql:
          condition: service_healthy
      environment:
        MYSQL_HOST: mysql
        MYSQL_USER: football
        MYSQL_PASSWORD: footballpassword
        FOOTBALL_API_TOKEN: 09c05f78fa8a44f8a2343532c1945ee6
        MYSQL_DATABASE: football
  
  frontend:
      build: frontend/.
      depends_on:
        mysql:
          condition: service_healthy
      environment:
        MYSQL_HOST: mysql
        MYSQL_USER: football
        MYSQL_PASSWORD: footballpassword
        FOOTBALL_API_TOKEN: 09c05f78fa8a44f8a2343532c1945ee6
        MYSQL_DATABASE: football
        ports:
          - "8000:8000"