services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: football
      MYSQL_USER: football
      MYSQL_PASSWORD: footballpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingestion:
    build: data_ingestion/.
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: football
      MYSQL_PASSWORD: footballpassword
      FOOTBALL_API_TOKEN: 09c05f78fa8a44f8a2343532c1945ee6
      MYSQL_DATABASE: football
  web:
    build: web/.
    depends_on:
      - mysql
      - ingestion
    ports:
      - "8000:8000"